name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        env:
          - name: ofutun-linux-amd64
            os: linux
            arch: amd64
          - name: ofutun-linux-arm64
            os: linux
            arch: arm64
          - name: ofutun-darwin-amd64
            os: darwin
            arch: amd64
          - name: ofutun-darwin-arm64
            os: darwin
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.env.os }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.env.arch }}" >> $GITHUB_ENV
          echo "CGO_ENABLED=0" >> $GITHUB_ENV

      - name: Build
        run: go build -o bin/main cmd/main.go

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          name: ${{ matrix.env.name }}-${{ github.event.ref }}
          path: bin/main
